name: Documentation

on:
  push:
    branches: [pages]

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      pages: write
      id-token: write
    steps:
    - run: pip install sphinx sphinx-rtd-theme
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: sphinx apidoc generation
      shell: bash -l {0}
      working-directory: ./docs
      run: |
        echo ::group::Sphinx apidocs generation
        sphinx-apidoc -o . ../stable_gnn
        echo ::endgroup::
        echo ::group::Sphinx docs compilation
        sphinx-build -M html . _build
        echo ::endgroup::
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
